from turtle import*

#design de la carte
def carte(x,y):
    #contour de la carte 
    k=0
    up()
    goto(x,y)
    down()
    color("black")
    while k<2:
        forward(81)
        left(90)
        forward(111)
        left(90)
        k=k+1
    left(90)
    up()
    forward(1)
    right(90)
    color("white")

    begin_fill()
    forward(80)
    left(90)
    forward(110)
    left(90)
    forward(80)
    left(90)
    forward(110)
    left(90)
    end_fill()

    #intérieur de la carte
    up()
    forward(10)
    left(180)
    right(90)
    forward(10)
    down()
    color("red")
    begin_fill()
    forward(90)
    right(90)
    forward(60)
    right(90)
    forward(90)
    right(90)
    forward(60)
    right(90)
    end_fill()

    up()
    forward(20)
    right(90)
    forward(30)
    down()
    color("white")
    begin_fill()
    circle(25,360)
    end_fill()
    
    #étoile centrale
    color("black")
    up()
    left(180)
    forward(4)
    right(90)
    down()
    begin_fill()
    z=0
    while z<5:
        forward(50)
        right(160)
        forward(50)
        right(160)
        z=z+1
    end_fill()

    #4 points dans les coins
    up()
    left(95)
    forward(30)
    down()
    color("black")
    begin_fill()
    circle(2,360)
    end_fill()
    up()
    left(150)
    forward(45)
    down()
    begin_fill()
    circle(2,360)
    end_fill()
    up()
    left(92)
    forward(80)
    down()
    begin_fill()
    circle(2,360)
    end_fill()
    up()
    left(90)
    forward(50)
    down()
    begin_fill()
    circle(2,360)
    end_fill()
    up()
    goto(x,y)
    left(3)
    down()
    
